<?php
/**
 * handles codewar parsing and output
 * codewar.module
 * 12/13/12 Mojiferous
 */

require_once('code_bot.inc');

/**
 * implements hook_menu()
 */
function codewar_menu() {
  $items = array();

  $items['code/%node'] = array(
    'title' => 'Code test output',
    'description' => 'Test output for codewar',
    'page callback' => 'codewar_render_code',
    'page arguments' => array(1),
    'access callback' => true,
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function codewar_render_code($node) {
  $this_body = field_get_items('node', $node, 'body');
  $raw_body = '';

  if(isset($this_body[0])) {
    $raw_body = $this_body[0]['value'];
  }

  $raw_body = str_replace("\n", ' ', $raw_body);
  $raw_body = str_replace("\r", ' ', $raw_body);
  $raw_body = str_replace('  ', ' ', $raw_body);

  //divide the body into lines
  $body_parts = explode(" ", $raw_body);

  $output = '';

  $this_code = new code_bot($body_parts);
  $this_code->parse_code();
  $code_array = $this_code->code_array;
  drupal_add_js(array('bot_code' => $code_array), 'setting');


  dpm($code_array);

  dpm($raw_body);

  return $output;
}